import { Question } from '../types.ts';

export const ALL_QUESTIONS: Question[] = [
  {
    problem: 'Contains Duplicate',
    pattern: 'Arrays & Hashing',
    link: 'contains-duplicate/',
    difficulty: 'easy',
    video: '3OamzN90kPg',
  },
  {
    problem: 'Valid Anagram',
    pattern: 'Arrays & Hashing',
    link: 'valid-anagram/',
    difficulty: 'easy',
    video: '9UtInBqnCgA',
  },
  {
    problem: 'Concatenation of Array',
    pattern: 'Arrays & Hashing',
    link: 'concatenation-of-array/',
    difficulty: 'easy',
    video: '68isPRHgcFQ',
  },
  {
    problem: 'Replace Elements With Greatest Element On Right Side',
    pattern: 'Arrays & Hashing',
    link: 'replace-elements-with-greatest-element-on-right-side/',
    difficulty: 'easy',
    video: 'ZHjKhUjcsaU',
  },
  {
    problem: 'Is Subsequence',
    pattern: 'Arrays & Hashing',
    link: 'is-subsequence/',
    difficulty: 'easy',
    video: '99RVfqklbCE',
  },
  {
    problem: 'Length of Last Word',
    pattern: 'Arrays & Hashing',
    link: 'length-of-last-word/',
    difficulty: 'easy',
    video: 'KT9rltZTybQ',
  },
  {
    problem: 'Two Sum',
    pattern: 'Arrays & Hashing',
    link: 'two-sum/',
    difficulty: 'easy',
    video: 'KLlXCFG5TnA',
  },
  {
    problem: 'Longest Common Prefix',
    pattern: 'Arrays & Hashing',
    link: 'longest-common-prefix/',
    difficulty: 'easy',
    video: '0sWShKIJoo4',
  },
  {
    problem: 'Group Anagrams',
    pattern: 'Arrays & Hashing',
    link: 'group-anagrams/',
    difficulty: 'medium',
    video: 'vzdNOK2oB2E',
  },
  {
    problem: 'Pascals Triangle',
    pattern: 'Arrays & Hashing',
    link: 'pascals-triangle/',
    difficulty: 'easy',
    video: 'nPVEaB3AjUM',
  },
  {
    problem: 'Remove Element',
    pattern: 'Arrays & Hashing',
    link: 'remove-element/',
    difficulty: 'easy',
    video: 'Pcd1ii9P9ZI',
  },
  {
    problem: 'Unique Email Addresses',
    pattern: 'Arrays & Hashing',
    link: 'unique-email-addresses/',
    difficulty: 'easy',
    video: 'TC_xLIWl7qY',
  },
  {
    problem: 'Isomorphic Strings',
    pattern: 'Arrays & Hashing',
    link: 'isomorphic-strings/',
    difficulty: 'easy',
    video: '7yF-U1hLEqQ',
  },
  {
    problem: 'Can Place Flowers',
    pattern: 'Arrays & Hashing',
    link: 'can-place-flowers/',
    difficulty: 'easy',
    video: 'ZGxqqjljpUI',
  },
  {
    problem: 'Majority Element',
    pattern: 'Arrays & Hashing',
    link: 'majority-element/',
    difficulty: 'easy',
    video: '7pnhv842keE',
  },
  {
    problem: 'Next Greater Element I',
    pattern: 'Arrays & Hashing',
    link: 'next-greater-element-i/',
    difficulty: 'easy',
    video: '68a1Dc_qVq4',
  },
  {
    problem: 'Find Pivot Index',
    pattern: 'Arrays & Hashing',
    link: 'find-pivot-index/',
    difficulty: 'easy',
    video: 'u89i60lYx8U',
  },
  {
    problem: 'Range Sum Query - Immutable',
    pattern: 'Arrays & Hashing',
    link: 'range-sum-query-immutable/',
    difficulty: 'easy',
    video: '2pndAmo_sMA',
  },
  {
    problem: 'Find All Numbers Disappeared in An Array',
    pattern: 'Arrays & Hashing',
    link: 'find-all-numbers-disappeared-in-an-array/',
    difficulty: 'easy',
    video: '8i-f24YFWC4',
  },
  {
    problem: 'Maximum Number of Balloons',
    pattern: 'Arrays & Hashing',
    link: 'maximum-number-of-balloons/',
    difficulty: 'easy',
    video: 'G9xeB2-7PqY',
  },
  {
    problem: 'Word Pattern',
    pattern: 'Arrays & Hashing',
    link: 'word-pattern/',
    difficulty: 'easy',
    video: 'W_akoecmCbM',
  },
  {
    problem: 'Design HashSet',
    pattern: 'Arrays & Hashing',
    link: 'design-hashset/',
    difficulty: 'easy',
    video: 'VymjPQUXjL8',
  },
  {
    problem: 'Design HashMap',
    pattern: 'Arrays & Hashing',
    link: 'design-hashmap/',
    difficulty: 'easy',
    video: 'cNWsgbKwwoU',
  },
  {
    problem: 'Sort an Array',
    pattern: 'Arrays & Hashing',
    link: 'sort-an-array/',
    difficulty: 'medium',
    video: 'MsYZSinhuFo',
  },
  {
    problem: 'Top K Frequent Elements',
    pattern: 'Arrays & Hashing',
    link: 'top-k-frequent-elements/',
    difficulty: 'medium',
    video: 'YPTqKIgVk-k',
  },
  {
    problem: 'Product of Array Except Self',
    pattern: 'Arrays & Hashing',
    link: 'product-of-array-except-self/',
    difficulty: 'medium',
    video: 'bNvIQI2wAjk',
  },
  {
    problem: 'Valid Sudoku',
    pattern: 'Arrays & Hashing',
    link: 'valid-sudoku/',
    difficulty: 'medium',
    video: 'TjFXEUCMqI8',
  },
  {
    problem: 'Encode and Decode Strings',
    pattern: 'Arrays & Hashing',
    link: 'encode-and-decode-strings/',
    difficulty: 'medium',
    video: 'B1k_sxOSgv8',
  },
  {
    problem: 'Longest Consecutive Sequence',
    pattern: 'Arrays & Hashing',
    link: 'longest-consecutive-sequence/',
    difficulty: 'medium',
    video: 'P6RZZMu_maU',
  },
  {
    problem: 'Sort Colors',
    pattern: 'Arrays & Hashing',
    link: 'sort-colors/',
    difficulty: 'medium',
    video: '4xbWSRZHqac',
  },
  {
    problem: 'Encode and Decode TinyURL',
    pattern: 'Arrays & Hashing',
    link: 'encode-and-decode-tinyurl/',
    difficulty: 'medium',
    video: 'VyBOaboQLGc',
  },
  {
    problem: 'Brick Wall',
    pattern: 'Arrays & Hashing',
    link: 'brick-wall/',
    difficulty: 'medium',
    video: 'Kkmv2h48ekw',
  },
  {
    problem: 'Best Time to Buy And Sell Stock II',
    pattern: 'Arrays & Hashing',
    link: 'best-time-to-buy-and-sell-stock-ii/',
    difficulty: 'medium',
    video: '3SJ3pUkPQMc',
  },
  {
    problem: 'Subarray Sum Equals K',
    pattern: 'Arrays & Hashing',
    link: 'subarray-sum-equals-k/',
    difficulty: 'medium',
    video: 'fFVZt-6sgyo',
  },
  {
    problem: 'Unique Length 3 Palindromic Subsequences',
    pattern: 'Arrays & Hashing',
    link: 'unique-length-3-palindromic-subsequences/',
    difficulty: 'medium',
    video: '3THUt0vAFLU',
  },
  {
    problem: 'Minimum Number of Swaps to Make The String Balanced',
    pattern: 'Arrays & Hashing',
    link: 'minimum-number-of-swaps-to-make-the-string-balanced/',
    difficulty: 'medium',
    video: '3YDBT9ZrfaU',
  },
  {
    problem: 'Number of Pairs of Interchangeable Rectangles',
    pattern: 'Arrays & Hashing',
    link: 'number-of-pairs-of-interchangeable-rectangles/',
    difficulty: 'medium',
    video: 'lEQ8ZlLOuyQ',
  },
  {
    problem: 'Maximum Product of The Length of Two Palindromic Subsequences',
    pattern: 'Arrays & Hashing',
    link: 'maximum-product-of-the-length-of-two-palindromic-subsequences/',
    difficulty: 'medium',
    video: 'aoHbYlO8vDg',
  },
  {
    problem: 'Grid Game',
    pattern: 'Arrays & Hashing',
    link: 'grid-game/',
    difficulty: 'medium',
    video: 'N4wDSOw65hI',
  },
  {
    problem: 'Find All Anagrams in a String',
    pattern: 'Arrays & Hashing',
    link: 'find-all-anagrams-in-a-string/',
    difficulty: 'medium',
    video: 'G8xtZy0fDKg',
  },
  {
    problem: 'Find The Index of The First Occurrence in a String',
    pattern: 'Arrays & Hashing',
    link: 'find-the-index-of-the-first-occurrence-in-a-string/',
    difficulty: 'easy',
    video: 'JoF0Z7nVSrA',
  },
  {
    problem: 'Wiggle Sort',
    pattern: 'Arrays & Hashing',
    link: 'wiggle-sort/',
    difficulty: 'medium',
    video: 'vGsyTE4s34w',
  },
  {
    problem: 'Largest Number',
    pattern: 'Arrays & Hashing',
    link: 'largest-number/',
    difficulty: 'medium',
    video: 'WDx6Y4i4xJ8',
  },
  {
    problem: 'Continuous Subarray Sum',
    pattern: 'Arrays & Hashing',
    link: 'continuous-subarray-sum/',
    difficulty: 'medium',
    video: 'OKcrLfR-8mE',
  },
  {
    problem: 'Push Dominoes',
    pattern: 'Arrays & Hashing',
    link: 'push-dominoes/',
    difficulty: 'medium',
    video: 'evUFsOb_iLY',
  },
  {
    problem: 'Repeated DNA Sequences',
    pattern: 'Arrays & Hashing',
    link: 'repeated-dna-sequences/',
    difficulty: 'medium',
    video: 'FzTYfsmtOso',
  },
  {
    problem: 'Insert Delete Get Random O(1)',
    pattern: 'Arrays & Hashing',
    link: 'insert-delete-getrandom-o1/',
    difficulty: 'medium',
    video: 'j4KwhBziOpg',
  },
  {
    problem: 'Check if a String Contains all Binary Codes of Size K',
    pattern: 'Arrays & Hashing',
    link: 'check-if-a-string-contains-all-binary-codes-of-size-k/',
    difficulty: 'medium',
    video: 'qU32rTy_kOM',
  },
  {
    problem: 'Range Sum Query 2D Immutable',
    pattern: 'Arrays & Hashing',
    link: 'range-sum-query-2d-immutable/',
    difficulty: 'medium',
    video: 'KE8MQuwE2yA',
  },
  {
    problem: 'Non Decreasing Array',
    pattern: 'Arrays & Hashing',
    link: 'non-decreasing-array/',
    difficulty: 'medium',
    video: 'RegQckCegDk',
  },
  {
    problem: 'First Missing Positive',
    pattern: 'Arrays & Hashing',
    link: 'first-missing-positive/',
    difficulty: 'hard',
    video: '8g78yfzMlao',
  },
  {
    problem: 'Sign of An Array',
    pattern: 'Arrays & Hashing',
    link: 'sign-of-the-product-of-an-array/',
    difficulty: 'easy',
    video: 'ILDLM86jNow',
  },
  {
    problem: 'Find the Difference of Two Arrays',
    pattern: 'Arrays & Hashing',
    link: 'find-the-difference-of-two-arrays/',
    difficulty: 'easy',
    video: 'a4wqKR-znBE',
  },
  {
    problem: 'Design Parking System',
    pattern: 'Arrays & Hashing',
    link: 'design-parking-system/',
    difficulty: 'easy',
    video: 'd5zCHesOrSk',
  },
  {
    problem: 'Number of Zero-Filled Subarrays',
    pattern: 'Arrays & Hashing',
    link: 'number-of-zero-filled-subarrays/',
    difficulty: 'medium',
    video: 'G-EWVGCcL_w',
  },
  {
    problem: 'Optimal Partition of String',
    pattern: 'Arrays & Hashing',
    link: 'optimal-partition-of-string/',
    difficulty: 'medium',
    video: 'CKZPdiXiQf0',
  },
  {
    problem: 'Design Underground System',
    pattern: 'Arrays & Hashing',
    link: 'design-underground-system/',
    difficulty: 'medium',
    video: 'W5QOLqXskZM',
  },
  {
    problem: 'Naming a Company',
    pattern: 'Arrays & Hashing',
    link: 'naming-a-company/',
    difficulty: 'hard',
    video: 'NrHpgTScOcY',
  },
  {
    problem: 'Valid Palindrome',
    pattern: 'Two Pointers',
    link: 'valid-palindrome/',
    difficulty: 'easy',
    video: 'jJXJ16kPFWg',
  },
  {
    problem: 'Valid Palindrome II',
    pattern: 'Two Pointers',
    link: 'valid-palindrome-ii/',
    difficulty: 'easy',
    video: 'JrxRYBwG6EI',
  },
  {
    problem: 'Minimum Difference Between Highest And Lowest of K Scores',
    pattern: 'Two Pointers',
    link: 'minimum-difference-between-highest-and-lowest-of-k-scores/',
    difficulty: 'easy',
    video: 'JU5XdBZZtlk',
  },
  {
    problem: 'Merge Strings Alternately',
    pattern: 'Two Pointers',
    link: 'merge-strings-alternately/',
    difficulty: 'easy',
    video: 'LECWOvTo-Sc',
  },
  {
    problem: 'Reverse String',
    pattern: 'Two Pointers',
    link: 'reverse-string/',
    difficulty: 'easy',
    video: '_d0T_2Lk2qA',
  },
  {
    problem: 'Merge Sorted Array',
    pattern: 'Two Pointers',
    link: 'merge-sorted-array/',
    difficulty: 'easy',
    video: 'P1Ic85RarKY',
  },
  {
    problem: 'Move Zeroes',
    pattern: 'Two Pointers',
    link: 'move-zeroes/',
    difficulty: 'easy',
    video: 'aayNRwUN3Do',
  },
  {
    problem: 'Remove Duplicates From Sorted Array',
    pattern: 'Two Pointers',
    link: 'remove-duplicates-from-sorted-array/',
    difficulty: 'easy',
    video: 'DEJAZBq0FDA',
  },
  {
    problem: 'Remove Duplicates From Sorted Array II',
    pattern: 'Two Pointers',
    link: 'remove-duplicates-from-sorted-array-ii/',
    difficulty: 'medium',
    video: 'ycAq8iqh0TI',
  },
  {
    problem: 'Two Sum II Input Array Is Sorted',
    pattern: 'Two Pointers',
    link: 'two-sum-ii-input-array-is-sorted/',
    difficulty: 'medium',
    video: 'cQ1Oz4ckceM',
  },
  {
    problem: '3Sum',
    pattern: 'Two Pointers',
    link: '3sum/',
    difficulty: 'medium',
    video: 'jzZsG8n2R9A',
  },
  {
    problem: '4Sum',
    pattern: 'Two Pointers',
    link: '4sum/',
    difficulty: 'medium',
    video: 'EYeR-_1NRlQ',
  },
  {
    problem: 'Container With Most Water',
    pattern: 'Two Pointers',
    link: 'container-with-most-water/',
    difficulty: 'medium',
    video: 'UuiTKBwPgAo',
  },
  {
    problem: 'Number of Subsequences That Satisfy The Given Sum Condition',
    pattern: 'Two Pointers',
    link: 'number-of-subsequences-that-satisfy-the-given-sum-condition/',
    difficulty: 'medium',
    video: 'xCsIkPLS4Ls',
  },
  {
    problem: 'Rotate Array',
    pattern: 'Two Pointers',
    link: 'rotate-array/',
    difficulty: 'medium',
    video: 'BHr381Guz3Y',
  },
  {
    problem: 'Array With Elements Not Equal to Average of Neighbors',
    pattern: 'Two Pointers',
    link: 'array-with-elements-not-equal-to-average-of-neighbors/',
    difficulty: 'medium',
    video: 'Wmb3YdVYfqM',
  },
  {
    problem: 'Boats to Save People',
    pattern: 'Two Pointers',
    link: 'boats-to-save-people/',
    difficulty: 'medium',
    video: 'XbaxWuHIWUs',
  },
  {
    problem: 'Trapping Rain Water',
    pattern: 'Two Pointers',
    link: 'trapping-rain-water/',
    difficulty: 'hard',
    video: 'ZI2z5pq0TqA',
  },
  {
    problem: 'Best Time to Buy And Sell Stock',
    pattern: 'Sliding Window',
    link: 'best-time-to-buy-and-sell-stock/',
    difficulty: 'easy',
    video: '1pkOgXD63yU',
  },
  {
    problem: 'Contains Duplicate II',
    pattern: 'Sliding Window',
    link: 'contains-duplicate-ii/',
    difficulty: 'easy',
    video: 'ypn0aZ0nrL4',
  },
  {
    problem:
      'Number of Sub Arrays of Size K and Avg Greater than or Equal to Threshold',
    pattern: 'Sliding Window',
    link: 'number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/',
    difficulty: 'medium',
    video: 'D8B4tKxMTnY',
  },
  {
    problem: 'Longest Substring Without Repeating Characters',
    pattern: 'Sliding Window',
    link: 'longest-substring-without-repeating-characters/',
    difficulty: 'medium',
    video: 'wiGpQwVHdE0',
  },
  {
    problem: 'Longest Repeating Character Replacement',
    pattern: 'Sliding Window',
    link: 'longest-repeating-character-replacement/',
    difficulty: 'medium',
    video: 'gqXU1UyA8pk',
  },
  {
    problem: 'Permutation In String',
    pattern: 'Sliding Window',
    link: 'permutation-in-string/',
    difficulty: 'medium',
    video: 'UbyhOgBN834',
  },
  {
    problem: 'Frequency of The Most Frequent Element',
    pattern: 'Sliding Window',
    link: 'frequency-of-the-most-frequent-element/',
    difficulty: 'medium',
    video: 'vgBrQ0NM5vE',
  },
  {
    problem: 'Fruits into Basket',
    pattern: 'Sliding Window',
    link: 'fruit-into-baskets/',
    difficulty: 'medium',
    video: 'yYtaV0G3mWQ',
  },
  {
    problem: 'Maximum Number of Vowels in a Substring of Given Length',
    pattern: 'Sliding Window',
    link: 'maximum-number-of-vowels-in-a-substring-of-given-length/',
    difficulty: 'medium',
    video: 'kEfPSzgL-Ss',
  },
  {
    problem: 'Minimum Number of Flips to Make The Binary String Alternating',
    pattern: 'Sliding Window',
    link: 'minimum-number-of-flips-to-make-the-binary-string-alternating/',
    difficulty: 'medium',
    video: 'MOeuK6gaC2A',
  },
  {
    problem: 'Minimum Size Subarray Sum',
    pattern: 'Sliding Window',
    link: 'minimum-size-subarray-sum/',
    difficulty: 'medium',
    video: 'aYqYMIqZx5s',
  },
  {
    problem: 'Find K Closest Elements',
    pattern: 'Sliding Window',
    link: 'find-k-closest-elements/',
    difficulty: 'medium',
    video: 'o-YDQzHoaKM',
  },
  {
    problem: 'Minimum Window Substring',
    pattern: 'Sliding Window',
    link: 'minimum-window-substring/',
    difficulty: 'hard',
    video: 'jSto0O4AJbM',
  },
  {
    problem: 'Sliding Window Maximum',
    pattern: 'Sliding Window',
    link: 'sliding-window-maximum/',
    difficulty: 'hard',
    video: 'DfljaUwZsOk',
  },
  {
    problem: 'Valid Parentheses',
    pattern: 'Stack',
    link: 'valid-parentheses/',
    difficulty: 'easy',
    video: 'WTzjTskDFMg',
  },
  {
    problem: 'Baseball Game',
    pattern: 'Stack',
    link: 'baseball-game/',
    difficulty: 'easy',
    video: 'Id_tqGdsZQI',
  },
  {
    problem: 'Implement Stack Using Queues',
    pattern: 'Stack',
    link: 'implement-stack-using-queues/',
    difficulty: 'easy',
    video: 'rW4vm0-DLYc',
  },
  {
    problem: 'Min Stack',
    pattern: 'Stack',
    link: 'min-stack/',
    difficulty: 'medium',
    video: 'qkLl7nAwDPo',
  },
  {
    problem: 'Evaluate Reverse Polish Notation',
    pattern: 'Stack',
    link: 'evaluate-reverse-polish-notation/',
    difficulty: 'medium',
    video: 'iu0082c4HDE',
  },
  {
    problem: 'Removing Stars From a String',
    pattern: 'Stack',
    link: 'removing-stars-from-a-string/',
    difficulty: 'medium',
    video: 'pRyFZIaKegA',
  },
  {
    problem: 'Validate Stack Sequences',
    pattern: 'Stack',
    link: 'validate-stack-sequences/',
    difficulty: 'medium',
    video: 'mzua0r94kb8',
  },
  {
    problem: 'Generate Parentheses',
    pattern: 'Stack',
    link: 'generate-parentheses/',
    difficulty: 'medium',
    video: 's9fokUqJ76A',
  },
  {
    problem: 'Asteroid Collision',
    pattern: 'Stack',
    link: 'asteroid-collision/',
    difficulty: 'medium',
    video: 'LN7KjRszjk4',
  },
  {
    problem: 'Daily Temperatures',
    pattern: 'Stack',
    link: 'daily-temperatures/',
    difficulty: 'medium',
    video: 'cTBiBSnjO3c',
  },
  {
    problem: 'Online Stock Span',
    pattern: 'Stack',
    link: 'online-stock-span/',
    difficulty: 'medium',
    video: 'slYh0ZNEqSw',
  },
  {
    problem: 'Car Fleet',
    pattern: 'Stack',
    link: 'car-fleet/',
    difficulty: 'medium',
    video: 'Pr6T-3yB9RM',
  },
  {
    problem: 'Simplify Path',
    pattern: 'Stack',
    link: 'simplify-path/',
    difficulty: 'medium',
    video: 'qYlHrAKJfyA',
  },
  {
    problem: 'Decode String',
    pattern: 'Stack',
    link: 'decode-string/',
    difficulty: 'medium',
    video: 'qB0zZpBJlh8',
  },
  {
    problem: 'Remove K Digits',
    pattern: 'Stack',
    link: 'remove-k-digits/',
    difficulty: 'medium',
    video: 'cFabMOnJaq0',
  },
  {
    problem: 'Remove All Adjacent Duplicates In String II',
    pattern: 'Stack',
    link: 'remove-all-adjacent-duplicates-in-string-ii/',
    difficulty: 'medium',
    video: 'w6LcypDgC4w',
  },
  {
    problem: '132 Pattern',
    pattern: 'Stack',
    link: '132-pattern/',
    difficulty: 'medium',
    video: 'q5ANAl8Z458',
  },
  {
    problem: 'Maximum Frequency Stack',
    pattern: 'Stack',
    link: 'maximum-frequency-stack/',
    difficulty: 'hard',
    video: 'Z6idIicFDOE',
  },
  {
    problem: 'Largest Rectangle In Histogram',
    pattern: 'Stack',
    link: 'largest-rectangle-in-histogram/',
    difficulty: 'hard',
    video: 'zx5Sw9130L0',
  },
  {
    problem: 'Binary Search',
    pattern: 'Binary Search',
    link: 'binary-search/',
    difficulty: 'easy',
    video: 's4DPM8ct1pI',
  },
  {
    problem: 'Search Insert Position',
    pattern: 'Binary Search',
    link: 'search-insert-position/',
    difficulty: 'easy',
    video: 'K-RYzDZkzCI',
  },
  {
    problem: 'Guess Number Higher Or Lower',
    pattern: 'Binary Search',
    link: 'guess-number-higher-or-lower/',
    difficulty: 'easy',
    video: 'xW4QsTtaCa4',
  },
  {
    problem: 'Arranging Coins',
    pattern: 'Binary Search',
    link: 'arranging-coins/',
    difficulty: 'easy',
    video: '5rHz_6s2Buw',
  },
  {
    problem: 'Squares of a Sorted Array',
    pattern: 'Binary Search',
    link: 'squares-of-a-sorted-array/',
    difficulty: 'easy',
    video: 'FPCZsG_AkUg',
  },
  {
    problem: 'Valid Perfect Square',
    pattern: 'Binary Search',
    link: 'valid-perfect-square/',
    difficulty: 'easy',
    video: 'Cg_wWPHJ2Sk',
  },
  {
    problem: 'Sqrt(x) ',
    pattern: 'Binary Search',
    link: 'sqrtx/',
    difficulty: 'easy',
    video: 'zdMhGxRWutQ',
  },
  {
    problem: 'Single Element in a Sorted Array',
    pattern: 'Binary Search',
    link: 'single-element-in-a-sorted-array/',
    difficulty: 'medium',
    video: 'HGtqdzyUJ3k',
  },
  {
    problem: 'Capacity to Ship Packages',
    pattern: 'Binary Search',
    link: 'capacity-to-ship-packages-within-d-days/',
    difficulty: 'medium',
    video: 'ER_oLmdc-nw',
  },
  {
    problem: 'Find Peak Element',
    pattern: 'Binary Search',
    link: 'find-peak-element/',
    difficulty: 'medium',
    video: 'kMzJy9es7Hc',
  },
  {
    problem: 'Successful Pairs of Spells and Potions',
    pattern: 'Binary Search',
    link: 'successful-pairs-of-spells-and-potions/',
    difficulty: 'medium',
    video: 'OKnm5oyAhWg',
  },
  {
    problem: 'Search a 2D Matrix',
    pattern: 'Binary Search',
    link: 'search-a-2d-matrix/',
    difficulty: 'medium',
    video: 'Ber2pi2C0j0',
  },
  {
    problem: 'Koko Eating Bananas',
    pattern: 'Binary Search',
    link: 'koko-eating-bananas/',
    difficulty: 'medium',
    video: 'U2SozAs9RzA',
  },
  {
    problem: 'Find Minimum In Rotated Sorted Array',
    pattern: 'Binary Search',
    link: 'find-minimum-in-rotated-sorted-array/',
    difficulty: 'medium',
    video: 'nIVW4P8b1VA',
  },
  {
    problem: 'Search In Rotated Sorted Array',
    pattern: 'Binary Search',
    link: 'search-in-rotated-sorted-array/',
    difficulty: 'medium',
    video: 'U8XENwh8Oy8',
  },
  {
    problem: 'Time Based Key Value Store',
    pattern: 'Binary Search',
    link: 'time-based-key-value-store/',
    difficulty: 'medium',
    video: 'fu2cD_6E8Hw',
  },
  {
    problem: 'Find First And Last Position of Element In Sorted Array',
    pattern: 'Binary Search',
    link: 'find-first-and-last-position-of-element-in-sorted-array/',
    difficulty: 'medium',
    video: '4sQL7R5ySUU',
  },
  {
    problem: 'Maximum Number of Removable Characters',
    pattern: 'Binary Search',
    link: 'maximum-number-of-removable-characters/',
    difficulty: 'medium',
    video: 'NMP3nRPyX5g',
  },
  {
    problem: 'Populating Next Right Pointers In Each Node',
    pattern: 'Binary Search',
    link: 'populating-next-right-pointers-in-each-node/',
    difficulty: 'medium',
    video: 'U4hFQCa1Cq0',
  },
  {
    problem: 'Search Suggestions System',
    pattern: 'Binary Search',
    link: 'search-suggestions-system/',
    difficulty: 'medium',
    video: 'D4T2N0yAr20',
  },
  {
    problem: 'Split Array Largest Sum',
    pattern: 'Binary Search',
    link: 'split-array-largest-sum/',
    difficulty: 'hard',
    video: 'YUF3_eBdzsk',
  },
  {
    problem: 'Median of Two Sorted Arrays',
    pattern: 'Binary Search',
    link: 'median-of-two-sorted-arrays/',
    difficulty: 'hard',
    video: 'q6IEA26hvXc',
  },
  {
    problem: 'Reverse Linked List',
    pattern: 'Linked List',
    link: 'reverse-linked-list/',
    difficulty: 'easy',
    video: 'G0_I-ZF0S38',
  },
  {
    problem: 'Merge Two Sorted Lists',
    pattern: 'Linked List',
    link: 'merge-two-sorted-lists/',
    difficulty: 'easy',
    video: 'XIdigk956u0',
  },
  {
    problem: 'Palindrome Linked List',
    pattern: 'Linked List',
    link: 'palindrome-linked-list/',
    difficulty: 'easy',
    video: 'yOzXms1J6Nk',
  },
  {
    problem: 'Remove Linked List Elements',
    pattern: 'Linked List',
    link: 'remove-linked-list-elements/',
    difficulty: 'easy',
    video: 'JI71sxtHTng',
  },
  {
    problem: 'Remove Duplicates From Sorted List',
    pattern: 'Linked List',
    link: 'remove-duplicates-from-sorted-list/',
    difficulty: 'easy',
    video: 'p10f-VpO4nE',
  },
  {
    problem: 'Middle of the Linked List',
    pattern: 'Linked List',
    link: 'middle-of-the-linked-list/',
    difficulty: 'easy',
    video: 'A2_ldqM4QcY',
  },
  {
    problem: 'Intersection of Two Linked Lists',
    pattern: 'Linked List',
    link: 'intersection-of-two-linked-lists/',
    difficulty: 'easy',
    video: 'D0X0BONOQhI',
  },
  {
    problem: 'Reorder List',
    pattern: 'Linked List',
    link: 'reorder-list/',
    difficulty: 'medium',
    video: 'S5bfdUTrKLM',
  },
  {
    problem: 'Maximum Twin Sum Of A Linked List',
    pattern: 'Linked List',
    link: 'maximum-twin-sum-of-a-linked-list/',
    difficulty: 'medium',
    video: 'doj95MelfSA',
  },
  {
    problem: 'Remove Nth Node From End of List',
    pattern: 'Linked List',
    link: 'remove-nth-node-from-end-of-list/',
    difficulty: 'medium',
    video: 'XVuQxVej6y8',
  },
  {
    problem: 'Swapping Nodes in a Linked List',
    pattern: 'Linked List',
    link: 'swapping-nodes-in-a-linked-list/',
    difficulty: 'medium',
    video: '4LsrgMyQIjQ',
  },
  {
    problem: 'LFU Cache',
    pattern: 'Linked List',
    link: 'lfu-cache/',
    difficulty: 'hard',
    video: 'bLEIHn-DgoA',
  },
  {
    problem: 'Copy List With Random Pointer',
    pattern: 'Linked List',
    link: 'copy-list-with-random-pointer/',
    difficulty: 'medium',
    video: '5Y2EiZST97Y',
  },
  {
    problem: 'Design Linked List',
    pattern: 'Linked List',
    link: 'design-linked-list/',
    difficulty: 'medium',
    video: 'Wf4QhpdVFQo',
  },
  {
    problem: 'Design Browser History',
    pattern: 'Linked List',
    link: 'design-browser-history/',
    difficulty: 'medium',
    video: 'i1G-kKnBu8k',
  },
  {
    problem: 'Add Two Numbers',
    pattern: 'Linked List',
    link: 'add-two-numbers/',
    difficulty: 'medium',
    video: 'wgFPrzTjm7s',
  },
  {
    problem: 'Linked List Cycle',
    pattern: 'Linked List',
    link: 'linked-list-cycle/',
    difficulty: 'easy',
    video: 'gBTe7lFR3vc',
  },
  {
    problem: 'Find The Duplicate Number',
    pattern: 'Linked List',
    link: 'find-the-duplicate-number/',
    difficulty: 'medium',
    video: 'wjYnzkAhcNk',
  },
  {
    problem: 'Swap Nodes In Pairs',
    pattern: 'Linked List',
    link: 'swap-nodes-in-pairs/',
    difficulty: 'medium',
    video: 'o811TZLAWOo',
  },
  {
    problem: 'Sort List',
    pattern: 'Linked List',
    link: 'sort-list/',
    difficulty: 'medium',
    video: 'TGveA1oFhrc',
  },
  {
    problem: 'Partition List',
    pattern: 'Linked List',
    link: 'partition-list/',
    difficulty: 'medium',
    video: 'KT1iUciJr4g',
  },
  {
    problem: 'Rotate List',
    pattern: 'Linked List',
    link: 'rotate-list/',
    difficulty: 'medium',
    video: 'UcGtPs2LE_c',
  },
  {
    problem: 'Reverse Linked List II',
    pattern: 'Linked List',
    link: 'reverse-linked-list-ii/',
    difficulty: 'medium',
    video: 'RF_M9tX4Eag',
  },
  {
    problem: 'Design Circular Queue',
    pattern: 'Linked List',
    link: 'design-circular-queue/',
    difficulty: 'medium',
    video: 'aBbsfn863oA',
  },
  {
    problem: 'Insertion Sort List',
    pattern: 'Linked List',
    link: 'insertion-sort-list/',
    difficulty: 'medium',
    video: 'Kk6mXAzqX3Y',
  },
  {
    problem: 'LRU Cache',
    pattern: 'Linked List',
    link: 'lru-cache/',
    difficulty: 'medium',
    video: '7ABFKPK2hD4',
  },
  {
    problem: 'Merge K Sorted Lists',
    pattern: 'Linked List',
    link: 'merge-k-sorted-lists/',
    difficulty: 'hard',
    video: 'q5a5OiGbT6Q',
  },
  {
    problem: 'Reverse Nodes In K Group',
    pattern: 'Linked List',
    link: 'reverse-nodes-in-k-group/',
    difficulty: 'hard',
    video: '1UOPsfP85V4',
  },
  {
    problem: 'Binary Tree Inorder Traversal',
    pattern: 'Trees',
    link: 'binary-tree-inorder-traversal/',
    difficulty: 'easy',
    video: 'g_S5WuasWUE',
  },
  {
    problem: 'Binary Tree Preorder Traversal',
    pattern: 'Trees',
    link: 'binary-tree-preorder-traversal/',
    difficulty: 'easy',
    video: 'afTpieEZXck',
  },
  {
    problem: 'Binary Tree Postorder Traversal',
    pattern: 'Trees',
    link: 'binary-tree-postorder-traversal/',
    difficulty: 'easy',
    video: 'QhszUQhGGlA',
  },
  {
    problem: 'Invert Binary Tree',
    pattern: 'Trees',
    link: 'invert-binary-tree/',
    difficulty: 'easy',
    video: 'OnSn2XEQ4MY',
  },
  {
    problem: 'Maximum Depth of Binary Tree',
    pattern: 'Trees',
    link: 'maximum-depth-of-binary-tree/',
    difficulty: 'easy',
    video: 'hTM3phVI6YQ',
  },
  {
    problem: 'Diameter of Binary Tree',
    pattern: 'Trees',
    link: 'diameter-of-binary-tree/',
    difficulty: 'easy',
    video: 'bkxqA8Rfv04',
  },
  {
    problem: 'Balanced Binary Tree',
    pattern: 'Trees',
    link: 'balanced-binary-tree/',
    difficulty: 'easy',
    video: 'QfJsau0ItOY',
  },
  {
    problem: 'Same Tree',
    pattern: 'Trees',
    link: 'same-tree/',
    difficulty: 'easy',
    video: 'vRbbcKXCxOw',
  },
  {
    problem: 'Subtree of Another Tree',
    pattern: 'Trees',
    link: 'subtree-of-another-tree/',
    difficulty: 'easy',
    video: 'E36O5SWp-LE',
  },
  {
    problem: 'Convert Sorted Array to Binary Search Tree',
    pattern: 'Trees',
    link: 'convert-sorted-array-to-binary-search-tree/',
    difficulty: 'easy',
    video: '0K0uCMYq5ng',
  },
  {
    problem: 'Merge Two Binary Trees',
    pattern: 'Trees',
    link: 'merge-two-binary-trees/',
    difficulty: 'easy',
    video: 'QHH6rIK3dDQ',
  },
  {
    problem: 'Path Sum',
    pattern: 'Trees',
    link: 'path-sum/',
    difficulty: 'easy',
    video: 'LSKQyOz_P8I',
  },
  {
    problem: 'Construct String From Binary Tree',
    pattern: 'Trees',
    link: 'construct-string-from-binary-tree/',
    difficulty: 'easy',
    video: 'b1WpYxnuebQ',
  },
  {
    problem: 'Lowest Common Ancestor of a Binary Search Tree',
    pattern: 'Trees',
    link: 'lowest-common-ancestor-of-a-binary-search-tree/',
    difficulty: 'medium',
    video: 'gs2LMfuOR9k',
  },
  {
    problem: 'Insert into a Binary Search Tree',
    pattern: 'Trees',
    link: 'insert-into-a-binary-search-tree/',
    difficulty: 'medium',
    video: 'Cpg8f79luEA',
  },
  {
    problem: 'Delete Node in a BST',
    pattern: 'Trees',
    link: 'delete-node-in-a-bst/',
    difficulty: 'medium',
    video: 'LFzAoJJt92M',
  },
  {
    problem: 'Binary Tree Level Order Traversal',
    pattern: 'Trees',
    link: 'binary-tree-level-order-traversal/',
    difficulty: 'medium',
    video: '6ZnyEApgFYg',
  },
  {
    problem: 'Binary Tree Right Side View',
    pattern: 'Trees',
    link: 'binary-tree-right-side-view/',
    difficulty: 'medium',
    video: 'd4zLyf32e3I',
  },
  {
    problem: 'Minimum Distance between BST Nodes',
    pattern: 'Trees',
    link: 'minimum-distance-between-bst-nodes/',
    difficulty: 'easy',
    video: 'joxx4hTYwcw',
  },
  {
    problem: 'Symmetric Tree ',
    pattern: 'Trees',
    link: 'symmetric-tree/',
    difficulty: 'easy',
    video: 'Mao9uzxwvmc',
  },
  {
    problem: 'Minimum Time to Collect All Apples in a Tree',
    pattern: 'Trees',
    link: 'minimum-time-to-collect-all-apples-in-a-tree/',
    difficulty: 'medium',
    video: 'Xdt5Z583auM',
  },
  {
    problem: 'Binary Tree Zigzag Level Order Traversal',
    pattern: 'Trees',
    link: 'binary-tree-zigzag-level-order-traversal/',
    difficulty: 'medium',
    video: 'igbboQbiwqw',
  },
  {
    problem: 'Construct Quad Tree',
    pattern: 'Trees',
    link: 'construct-quad-tree/',
    difficulty: 'medium',
    video: 'UQ-1sBMV0v4',
  },
  {
    problem: 'Find Duplicate Subtrees',
    pattern: 'Trees',
    link: 'find-duplicate-subtrees/',
    difficulty: 'medium',
    video: 'kn0Z5_qPPzY',
  },
  {
    problem: 'Check Completeness of a Binary Tree',
    pattern: 'Trees',
    link: 'check-completeness-of-a-binary-tree/',
    difficulty: 'medium',
    video: 'olbiZ-EOSig',
  },
  {
    problem: 'Construct Binary Tree from Inorder and Postorder Traversal',
    pattern: 'Trees',
    link: 'construct-binary-tree-from-inorder-and-postorder-traversal/',
    difficulty: 'medium',
    video: 'vm63HuIU7kw',
  },
  {
    problem: 'Maximum Width of Binary Tree ',
    pattern: 'Trees',
    link: 'maximum-width-of-binary-tree/',
    difficulty: 'medium',
    video: 'FPzLE2L7uHs',
  },
  {
    problem: 'Time Needed to Inform All Employees ',
    pattern: 'Trees',
    link: 'time-needed-to-inform-all-employees/',
    difficulty: 'medium',
    video: 'zdBYi0p4L5Q',
  },
  {
    problem: 'Count Good Nodes In Binary Tree',
    pattern: 'Trees',
    link: 'count-good-nodes-in-binary-tree/',
    difficulty: 'medium',
    video: '7cp5imvDzl4',
  },
  {
    problem: 'Validate Binary Search Tree',
    pattern: 'Trees',
    link: 'validate-binary-search-tree/',
    difficulty: 'medium',
    video: 's6ATEkipzow',
  },
  {
    problem: 'Kth Smallest Element In a Bst',
    pattern: 'Trees',
    link: 'kth-smallest-element-in-a-bst/',
    difficulty: 'medium',
    video: '5LUXSvjmGCw',
  },
  {
    problem: 'Construct Binary Tree From Preorder And Inorder Traversal',
    pattern: 'Trees',
    link: 'construct-binary-tree-from-preorder-and-inorder-traversal/',
    difficulty: 'medium',
    video: 'ihj4IQGZ2zc',
  },
  {
    problem: 'Unique Binary Search Trees',
    pattern: 'Trees',
    link: 'unique-binary-search-trees/',
    difficulty: 'medium',
    video: 'Ox0TenN3Zpg',
  },
  {
    problem: 'Sum Root to Leaf Numbers',
    pattern: 'Trees',
    link: 'sum-root-to-leaf-numbers/',
    difficulty: 'medium',
    video: 'Jk16lZGFWxE',
  },
  {
    problem: 'House Robber III',
    pattern: 'Trees',
    link: 'house-robber-iii/',
    difficulty: 'medium',
    video: 'nHR8ytpzz7c',
  },
  {
    problem: 'Flip Equivalent Binary Trees',
    pattern: 'Trees',
    link: 'flip-equivalent-binary-trees/',
    difficulty: 'medium',
    video: 'izRDc1il9Pk',
  },
  {
    problem: 'Operations On Tree',
    pattern: 'Trees',
    link: 'operations-on-tree/',
    difficulty: 'medium',
    video: 'qK4PtjrVD0U',
  },
  {
    problem: 'All Possible Full Binary Trees',
    pattern: 'Trees',
    link: 'all-possible-full-binary-trees/',
    difficulty: 'medium',
    video: 'nZtrZPTTCAo',
  },
  {
    problem: 'Find Bottom Left Tree Value',
    pattern: 'Trees',
    link: 'find-bottom-left-tree-value/',
    difficulty: 'medium',
    video: 'u_by_cTsNJA',
  },
  {
    problem: 'Trim a Binary Search Tree',
    pattern: 'Trees',
    link: 'trim-a-binary-search-tree/',
    difficulty: 'medium',
    video: 'jwt5mTjEXGc',
  },
  {
    problem: 'Binary Search Tree Iterator',
    pattern: 'Trees',
    link: 'binary-search-tree-iterator/',
    difficulty: 'medium',
    video: 'RXy5RzGF5wo',
  },
  {
    problem: 'Convert Bst to Greater Tree',
    pattern: 'Trees',
    link: 'convert-bst-to-greater-tree/',
    difficulty: 'medium',
    video: '7vVEJwVvAlI',
  },
  {
    problem: 'Binary Tree Maximum Path Sum',
    pattern: 'Trees',
    link: 'binary-tree-maximum-path-sum/',
    difficulty: 'hard',
    video: 'Hr5cWUld4vU',
  },
  {
    problem: 'Serialize And Deserialize Binary Tree',
    pattern: 'Trees',
    link: 'serialize-and-deserialize-binary-tree/',
    difficulty: 'hard',
    video: 'u4JAi2JJhI8',
  },
  {
    problem: 'Implement Trie Prefix Tree',
    pattern: 'Tries',
    link: 'implement-trie-prefix-tree/',
    difficulty: 'medium',
    video: 'oobqoCJlHA0',
  },
  {
    problem: 'Design Add And Search Words Data Structure',
    pattern: 'Tries',
    link: 'design-add-and-search-words-data-structure/',
    difficulty: 'medium',
    video: 'BTf05gs_8iU',
  },
  {
    problem: 'Word Search II',
    pattern: 'Tries',
    link: 'word-search-ii/',
    difficulty: 'hard',
    video: 'asbcE9mZz_U',
  },
  {
    problem: 'Kth Largest Element In a Stream',
    pattern: 'Heap / Priority Queue',
    link: 'kth-largest-element-in-a-stream/',
    difficulty: 'easy',
    video: 'hOjcdrqMoQ8',
  },
  {
    problem: 'Last Stone Weight',
    pattern: 'Heap / Priority Queue',
    link: 'last-stone-weight/',
    difficulty: 'easy',
    video: 'B-QCq79-Vfw',
  },
  {
    problem: 'K Closest Points to Origin',
    pattern: 'Heap / Priority Queue',
    link: 'k-closest-points-to-origin/',
    difficulty: 'medium',
    video: 'rI2EBUEMfTk',
  },
  {
    problem: 'Kth Largest Element In An Array',
    pattern: 'Heap / Priority Queue',
    link: 'kth-largest-element-in-an-array/',
    difficulty: 'medium',
    video: 'XEmy13g1Qxc',
  },
  {
    problem: 'Task Scheduler',
    pattern: 'Heap / Priority Queue',
    link: 'task-scheduler/',
    difficulty: 'medium',
    video: 's8p8ukTyA2I',
  },
  {
    problem: 'Design Twitter',
    pattern: 'Heap / Priority Queue',
    link: 'design-twitter/',
    difficulty: 'medium',
    video: 'pNichitDD2E',
  },
  {
    problem: 'Minimize Deviation in Array',
    pattern: 'Heap / Priority Queue',
    link: 'minimize-deviation-in-array/',
    difficulty: 'hard',
    video: 'boHNFptxo2A',
  },
  {
    problem: 'Maximum Subsequence Score',
    pattern: 'Heap / Priority Queue',
    link: 'maximum-subsequence-score/',
    difficulty: 'medium',
    video: 'ax1DKi5lJwk',
  },
  {
    problem: 'Single Threaded Cpu',
    pattern: 'Heap / Priority Queue',
    link: 'single-threaded-cpu/',
    difficulty: 'medium',
    video: 'RR1n-d4oYqE',
  },
  {
    problem: 'Seat Reservation Manager',
    pattern: 'Heap / Priority Queue',
    link: 'seat-reservation-manager/',
    difficulty: 'medium',
    video: 'ahobllKXEEY',
  },
  {
    problem: 'Process Tasks Using Servers',
    pattern: 'Heap / Priority Queue',
    link: 'process-tasks-using-servers/',
    difficulty: 'medium',
    video: 'XKA22PecuMQ',
  },
  {
    problem: 'Find The Kth Largest Integer In The Array',
    pattern: 'Heap / Priority Queue',
    link: 'find-the-kth-largest-integer-in-the-array/',
    difficulty: 'medium',
    video: 'lRCaNiqO3xI',
  },
  {
    problem: 'Reorganize String',
    pattern: 'Heap / Priority Queue',
    link: 'reorganize-string/',
    difficulty: 'medium',
    video: '2g_b1aYTHeg',
  },
  {
    problem: 'Longest Happy String',
    pattern: 'Heap / Priority Queue',
    link: 'longest-happy-string/',
    difficulty: 'medium',
    video: '8u-H6O_XQKE',
  },
  {
    problem: 'Car Pooling',
    pattern: 'Heap / Priority Queue',
    link: 'car-pooling/',
    difficulty: 'medium',
    video: '08sn_w4LWEE',
  },
  {
    problem: 'Find Median From Data Stream',
    pattern: 'Heap / Priority Queue',
    link: 'find-median-from-data-stream/',
    difficulty: 'hard',
    video: 'itmhHWaHupI',
  },
  {
    problem: 'Maximum Performance of a Team',
    pattern: 'Heap / Priority Queue',
    link: 'maximum-performance-of-a-team/',
    difficulty: 'hard',
    video: 'Y7UTvogADH0',
  },
  {
    problem: 'IPO',
    pattern: 'Heap / Priority Queue',
    link: 'ipo/',
    difficulty: 'hard',
    video: '1IUzNJ6TPEM',
  },
  {
    problem: 'Subsets',
    pattern: 'Backtracking',
    link: 'subsets/',
    difficulty: 'medium',
    video: 'REOH22Xwdkk',
  },
  {
    problem: 'Combination Sum',
    pattern: 'Backtracking',
    link: 'combination-sum/',
    difficulty: 'medium',
    video: 'GBKI9VSKdGg',
  },
  {
    problem: 'Combinations',
    pattern: 'Backtracking',
    link: 'combinations/',
    difficulty: 'medium',
    video: 'q0s6m7AiM7o',
  },
  {
    problem: 'Permutations',
    pattern: 'Backtracking',
    link: 'permutations/',
    difficulty: 'medium',
    video: 's7AvT7cGdSo',
  },
  {
    problem: 'Subsets II',
    pattern: 'Backtracking',
    link: 'subsets-ii/',
    difficulty: 'medium',
    video: 'Vn2v6ajA7U0',
  },
  {
    problem: 'Combination Sum II',
    pattern: 'Backtracking',
    link: 'combination-sum-ii/',
    difficulty: 'medium',
    video: 'rSA3t6BDDwg',
  },
  {
    problem: 'Permutations II',
    pattern: 'Backtracking',
    link: 'permutations-ii/',
    difficulty: 'medium',
    video: 'qhBVWf0YafA',
  },
  {
    problem: 'Word Search',
    pattern: 'Backtracking',
    link: 'word-search/',
    difficulty: 'medium',
    video: 'pfiQ_PS1g8E',
  },
  {
    problem: 'Palindrome Partitioning',
    pattern: 'Backtracking',
    link: 'palindrome-partitioning/',
    difficulty: 'medium',
    video: '3jvWodd7ht0',
  },
  {
    problem: 'Restore IP Addresses',
    pattern: 'Backtracking',
    link: 'restore-ip-addresses/',
    difficulty: 'medium',
    video: '61tN4YEdiTM',
  },
  {
    problem: 'Letter Combinations of a Phone Number',
    pattern: 'Backtracking',
    link: 'letter-combinations-of-a-phone-number/',
    difficulty: 'medium',
    video: '0snEunUacZY',
  },
  {
    problem: 'Matchsticks to Square',
    pattern: 'Backtracking',
    link: 'matchsticks-to-square/',
    difficulty: 'medium',
    video: 'hUe0cUKV-YY',
  },
  {
    problem: 'Splitting a String Into Descending Consecutive Values',
    pattern: 'Backtracking',
    link: 'splitting-a-string-into-descending-consecutive-values/',
    difficulty: 'medium',
    video: 'eDtMmysldaw',
  },
  {
    problem: 'Find Unique Binary String',
    pattern: 'Backtracking',
    link: 'find-unique-binary-string/',
    difficulty: 'medium',
    video: 'aHqn4Dynd1k',
  },
  {
    problem: 'Maximum Length of a Concatenated String With Unique Characters',
    pattern: 'Backtracking',
    link: 'maximum-length-of-a-concatenated-string-with-unique-characters/',
    difficulty: 'medium',
    video: 'd4SPuvkaeoo',
  },
  {
    problem: 'Partition to K Equal Sum Subsets',
    pattern: 'Backtracking',
    link: 'partition-to-k-equal-sum-subsets/',
    difficulty: 'medium',
    video: 'mBk4I0X46oI',
  },
  {
    problem: 'N Queens',
    pattern: 'Backtracking',
    link: 'n-queens/',
    difficulty: 'hard',
    video: 'Ph95IHmRp5M',
  },
  {
    problem: 'N Queens II',
    pattern: 'Backtracking',
    link: 'n-queens-ii/',
    difficulty: 'hard',
    video: 'nalYyLZgvCY',
  },
  {
    problem: 'Island Perimeter',
    pattern: 'Graphs',
    link: 'island-perimeter/',
    difficulty: 'easy',
    video: 'fISIuAFRM2s',
  },
  {
    problem: 'Verifying An Alien Dictionary',
    pattern: 'Graphs',
    link: 'verifying-an-alien-dictionary/',
    difficulty: 'easy',
    video: 'OVgPAJIyX6o',
  },
  {
    problem: 'Number of Islands',
    pattern: 'Graphs',
    link: 'number-of-islands/',
    difficulty: 'medium',
    video: 'pV2kpPD66nE',
  },
  {
    problem: 'Clone Graph',
    pattern: 'Graphs',
    link: 'clone-graph/',
    difficulty: 'medium',
    video: 'mQeF6bN8hMk',
  },
  {
    problem: 'Max Area of Island',
    pattern: 'Graphs',
    link: 'max-area-of-island/',
    difficulty: 'medium',
    video: 'iJGr1OtmH0c',
  },
  {
    problem: 'Count Sub Islands',
    pattern: 'Graphs',
    link: 'count-sub-islands/',
    difficulty: 'medium',
    video: 'mLpW3qfbNJ8',
  },
  {
    problem: 'Pacific Atlantic Water Flow',
    pattern: 'Graphs',
    link: 'pacific-atlantic-water-flow/',
    difficulty: 'medium',
    video: 's-VkcjHqkGI',
  },
  {
    problem: 'Surrounded Regions',
    pattern: 'Graphs',
    link: 'surrounded-regions/',
    difficulty: 'medium',
    video: '9z2BunfoZ5Y',
  },
  {
    problem: 'Reorder Routes to Make All Paths Lead to The City Zero',
    pattern: 'Graphs',
    link: 'reorder-routes-to-make-all-paths-lead-to-the-city-zero/',
    difficulty: 'medium',
    video: 'm17yOR5_PpI',
  },
  {
    problem: 'Rotting Oranges',
    pattern: 'Graphs',
    link: 'rotting-oranges/',
    difficulty: 'medium',
    video: 'y704fEOx0s0',
  },
  {
    problem: 'Walls And Gates',
    pattern: 'Graphs',
    link: 'walls-and-gates/',
    difficulty: 'medium',
    video: 'e69C6xhiSQE',
  },
  {
    problem: 'Snakes And Ladders',
    pattern: 'Graphs',
    link: 'snakes-and-ladders/',
    difficulty: 'medium',
    video: '6lH4nO3JfLk',
  },
  {
    problem: 'Open The Lock',
    pattern: 'Graphs',
    link: 'open-the-lock/',
    difficulty: 'medium',
    video: 'Pzg3bCDY87w',
  },
  {
    problem: 'Find Eventual Safe States',
    pattern: 'Graphs',
    link: 'find-eventual-safe-states/',
    difficulty: 'medium',
    video: 'Re_v0j0CRsg',
  },
  {
    problem: 'Course Schedule',
    pattern: 'Graphs',
    link: 'course-schedule/',
    difficulty: 'medium',
    video: 'EgI5nU9etnU',
  },
  {
    problem: 'Course Schedule II',
    pattern: 'Graphs',
    link: 'course-schedule-ii/',
    difficulty: 'medium',
    video: 'Akt3glAwyfY',
  },
  {
    problem: 'Course Schedule IV',
    pattern: 'Graphs',
    link: 'course-schedule-iv/',
    difficulty: 'medium',
    video: 'cEW05ofxhn0',
  },
  {
    problem: 'Check if Move Is Legal',
    pattern: 'Graphs',
    link: 'check-if-move-is-legal/',
    difficulty: 'medium',
    video: 'KxK33AcQZpQ',
  },
  {
    problem: 'Shortest Bridge',
    pattern: 'Graphs',
    link: 'shortest-bridge/',
    difficulty: 'medium',
    video: 'gkINMhbbIbU',
  },
  {
    problem: 'Shortest Path in Binary Matrix',
    pattern: 'Graphs',
    link: 'shortest-path-in-binary-matrix/',
    difficulty: 'medium',
    video: 'YnxUdAO7TAo',
  },
  {
    problem: 'Redundant Connection',
    pattern: 'Graphs',
    link: 'redundant-connection/',
    difficulty: 'medium',
    video: 'FXWRE67PLL0',
  },
  {
    problem: 'Number of Connected Components In An Undirected Graph',
    pattern: 'Graphs',
    link: 'number-of-connected-components-in-an-undirected-graph/',
    difficulty: 'medium',
    video: '8f1XPm4WOUc',
  },
  {
    problem: 'Graph Valid Tree',
    pattern: 'Graphs',
    link: 'graph-valid-tree/',
    difficulty: 'medium',
    video: 'bXsUuownnoQ',
  },
  {
    problem: 'Accounts Merge',
    pattern: 'Graphs',
    link: 'accounts-merge/',
    difficulty: 'medium',
    video: '6st4IxEF-90',
  },
  {
    problem: 'Find Closest Node to Given Two Nodes',
    pattern: 'Graphs',
    link: 'find-closest-node-to-given-two-nodes/',
    difficulty: 'medium',
    video: 'AZA8orksO4w',
  },
  {
    problem: 'As Far from Land as Possible',
    pattern: 'Graphs',
    link: 'as-far-from-land-as-possible/',
    difficulty: 'medium',
    video: 'fjxb1hQfrZk',
  },
  {
    problem: 'Shortest Path with Alternating Colors',
    pattern: 'Graphs',
    link: 'shortest-path-with-alternating-colors/',
    difficulty: 'medium',
    video: '69rcy6lb-HQ',
  },
  {
    problem: 'Minimum Fuel Cost to Report to the Capital',
    pattern: 'Graphs',
    link: 'minimum-fuel-cost-to-report-to-the-capital/',
    difficulty: 'medium',
    video: 'I3lnDUIzIG4',
  },
  {
    problem: 'Minimum Score of a Path Between Two Cities',
    pattern: 'Graphs',
    link: 'minimum-score-of-a-path-between-two-cities/',
    difficulty: 'medium',
    video: 'K7-mXA0irhY',
  },
  {
    problem: 'Number of Closed Islands',
    pattern: 'Graphs',
    link: 'number-of-closed-islands/',
    difficulty: 'medium',
    video: 'X8k48xek8g8',
  },
  {
    problem: 'Number of Enclaves',
    pattern: 'Graphs',
    link: 'number-of-enclaves/',
    difficulty: 'medium',
    video: 'gf0zsh1FIgE',
  },
  {
    problem: 'Minimum Number of Vertices to Reach all Nodes',
    pattern: 'Graphs',
    link: 'minimum-number-of-vertices-to-reach-all-nodes/',
    difficulty: 'medium',
    video: 'TLzcum7vrTc',
  },
  {
    problem: 'Is Graph Bipartite?',
    pattern: 'Graphs',
    link: 'is-graph-bipartite/',
    difficulty: 'medium',
    video: 'mev55LTubBY',
  },
  {
    problem: 'Evaluate Division',
    pattern: 'Graphs',
    link: 'evaluate-division/',
    difficulty: 'medium',
    video: 'Uei1fwDoyKk',
  },
  {
    problem: 'Detonate the Maximum Bombs',
    pattern: 'Graphs',
    link: 'detonate-the-maximum-bombs/',
    difficulty: 'medium',
    video: '8NPbAvVXKR4',
  },
  {
    problem: 'Largest Color Value in a Directed Graph',
    pattern: 'Graphs',
    link: 'largest-color-value-in-a-directed-graph/',
    difficulty: 'hard',
    video: 'xLoDjKczUSk',
  },
  {
    problem: 'Minimum Number of Days to Eat N Oranges',
    pattern: 'Graphs',
    link: 'minimum-number-of-days-to-eat-n-oranges/',
    difficulty: 'hard',
    video: 'LziQ6Qx9sks',
  },
  {
    problem: 'Word Ladder',
    pattern: 'Graphs',
    link: 'word-ladder/',
    difficulty: 'hard',
    video: 'h9iTnkgv05E',
  },
  {
    problem: 'Reconstruct Itinerary',
    pattern: 'Advanced Graphs',
    link: 'reconstruct-itinerary/',
    difficulty: 'hard',
    video: 'ZyB_gQ8vqGA',
  },
  {
    problem: 'Min Cost to Connect All Points',
    pattern: 'Advanced Graphs',
    link: 'min-cost-to-connect-all-points/',
    difficulty: 'medium',
    video: 'f7JOBJIC-NA',
  },
  {
    problem: 'Network Delay Time',
    pattern: 'Advanced Graphs',
    link: 'network-delay-time/',
    difficulty: 'medium',
    video: 'EaphyqKU4PQ',
  },
  {
    problem: 'Path with Maximum Probability',
    pattern: 'Advanced Graphs',
    link: 'path-with-maximum-probability/',
    difficulty: 'medium',
    video: 'kPsDTGcrzGM',
  },
  {
    problem: 'Swim In Rising Water',
    pattern: 'Advanced Graphs',
    link: 'swim-in-rising-water/',
    difficulty: 'hard',
    video: 'amvrKlMLuGY',
  },
  {
    problem: 'Alien Dictionary',
    pattern: 'Advanced Graphs',
    link: 'alien-dictionary/',
    difficulty: 'hard',
    video: '6kTZYvNNyps',
  },
  {
    problem: 'Cheapest Flights Within K Stops',
    pattern: 'Advanced Graphs',
    link: 'cheapest-flights-within-k-stops/',
    difficulty: 'medium',
    video: '5eIK3zUdYmE',
  },
  {
    problem: 'Number of Good Paths',
    pattern: 'Advanced Graphs',
    link: 'number-of-good-paths/',
    difficulty: 'hard',
    video: 'rv2GBYQm7xM',
  },
  {
    problem: 'Remove Max Number of Edges to Keep Graph Fully Traversable',
    pattern: 'Advanced Graphs',
    link: 'remove-max-number-of-edges-to-keep-graph-fully-traversable/',
    difficulty: 'hard',
    video: 'booGwg5wYm4',
  },
  {
    problem: 'Climbing Stairs',
    pattern: '1-D Dynamic Programming',
    link: 'climbing-stairs/',
    difficulty: 'easy',
    video: 'Y0lT9Fck7qI',
  },
  {
    problem: 'Min Cost Climbing Stairs',
    pattern: '1-D Dynamic Programming',
    link: 'min-cost-climbing-stairs/',
    difficulty: 'easy',
    video: 'ktmzAZWkEZ0',
  },
  {
    problem: 'House Robber',
    pattern: '1-D Dynamic Programming',
    link: 'house-robber/',
    difficulty: 'medium',
    video: '73r3KWiEvyk',
  },
  {
    problem: 'House Robber II',
    pattern: '1-D Dynamic Programming',
    link: 'house-robber-ii/',
    difficulty: 'medium',
    video: 'rWAJCfYYOvM',
  },
  {
    problem: 'Longest Palindromic Substring',
    pattern: '1-D Dynamic Programming',
    link: 'longest-palindromic-substring/',
    difficulty: 'medium',
    video: 'XYQecbcd6_c',
  },
  {
    problem: 'Palindromic Substrings',
    pattern: '1-D Dynamic Programming',
    link: 'palindromic-substrings/',
    difficulty: 'medium',
    video: '4RACzI5-du8',
  },
  {
    problem: 'Decode Ways',
    pattern: '1-D Dynamic Programming',
    link: 'decode-ways/',
    difficulty: 'medium',
    video: '6aEyTjOwlJU',
  },
  {
    problem: 'Coin Change',
    pattern: '1-D Dynamic Programming',
    link: 'coin-change/',
    difficulty: 'medium',
    video: 'H9bfqozjoqs',
  },
  {
    problem: 'Maximum Product Subarray',
    pattern: '1-D Dynamic Programming',
    link: 'maximum-product-subarray/',
    difficulty: 'medium',
    video: 'lXVy6YWFcRM',
  },
  {
    problem: 'Word Break',
    pattern: '1-D Dynamic Programming',
    link: 'word-break/',
    difficulty: 'medium',
    video: 'Sx9NNgInc3A',
  },
  {
    problem: 'Longest Increasing Subsequence',
    pattern: '1-D Dynamic Programming',
    link: 'longest-increasing-subsequence/',
    difficulty: 'medium',
    video: 'cjWnW0hdF1Y',
  },
  {
    problem: 'Partition Equal Subset Sum',
    pattern: '1-D Dynamic Programming',
    link: 'partition-equal-subset-sum/',
    difficulty: 'medium',
    video: 'IsvocB5BJhw',
  },
  {
    problem: 'Triangle',
    pattern: '1-D Dynamic Programming',
    link: 'triangle/',
    difficulty: 'medium',
    video: 'OM1MTokvxs4',
  },
  {
    problem: 'Delete And Earn',
    pattern: '1-D Dynamic Programming',
    link: 'delete-and-earn/',
    difficulty: 'medium',
    video: '7FCemBxvGw0',
  },
  {
    problem: 'Paint House',
    pattern: '1-D Dynamic Programming',
    link: 'paint-house/',
    difficulty: 'medium',
    video: '-w67-4tnH5U',
  },
  {
    problem: 'Combination Sum IV',
    pattern: '1-D Dynamic Programming',
    link: 'combination-sum-iv/',
    difficulty: 'medium',
    video: 'dw2nMCxG0ik',
  },
  {
    problem: 'Perfect Squares',
    pattern: '1-D Dynamic Programming',
    link: 'perfect-squares/',
    difficulty: 'medium',
    video: 'HLZLwjzIVGo',
  },
  {
    problem: 'Maximum Subarray Min Product',
    pattern: '1-D Dynamic Programming',
    link: 'maximum-subarray-min-product/',
    difficulty: 'medium',
    video: 'YLesLbNkyjA',
  },
  {
    problem: 'Minimum Cost For Tickets',
    pattern: '1-D Dynamic Programming',
    link: 'minimum-cost-for-tickets/',
    difficulty: 'medium',
    video: '4pY1bsBpIY4',
  },
  {
    problem: 'Integer Break',
    pattern: '1-D Dynamic Programming',
    link: 'integer-break/',
    difficulty: 'medium',
    video: 'in6QbUPMJ3I',
  },
  {
    problem: 'Number of Longest Increasing Subsequence',
    pattern: '1-D Dynamic Programming',
    link: 'number-of-longest-increasing-subsequence/',
    difficulty: 'medium',
    video: 'Tuc-rjJbsXU',
  },
  {
    problem: 'Stickers to Spell Word',
    pattern: '1-D Dynamic Programming',
    link: 'stickers-to-spell-word/',
    difficulty: 'hard',
    video: 'hsomLb6mUdI',
  },
  {
    problem: 'N-th Tribonacci Number',
    pattern: '1-D Dynamic Programming',
    link: 'n-th-tribonacci-number/',
    difficulty: 'easy',
    video: '3lpNp5Ojvrw',
  },
  {
    problem: 'Uncrossed Lines',
    pattern: '1-D Dynamic Programming',
    link: 'uncrossed-lines/',
    difficulty: 'medium',
    video: 'mnJF4vJ7GyE',
  },
  {
    problem: 'Solving Questions With Brainpower',
    pattern: '1-D Dynamic Programming',
    link: 'solving-questions-with-brainpower/',
    difficulty: 'medium',
    video: 'D7TD_ArkfkA',
  },
  {
    problem: 'Count Ways to Build Good Strings',
    pattern: '1-D Dynamic Programming',
    link: 'count-ways-to-build-good-strings/',
    difficulty: 'medium',
    video: 'JKpVHG2mhbk',
  },
  {
    problem: 'New 21 Game',
    pattern: '1-D Dynamic Programming',
    link: 'new-21-game/',
    difficulty: 'medium',
    video: 'zKi4LzjK27k',
  },
  {
    problem: 'Best Team with no Conflicts',
    pattern: '1-D Dynamic Programming',
    link: 'best-team-with-no-conflicts/',
    difficulty: 'medium',
    video: '7kURH3btcV4',
  },
  {
    problem: 'Stone Game III',
    pattern: '1-D Dynamic Programming',
    link: 'stone-game-iii/',
    difficulty: 'hard',
    video: 'HsLG5QW9CFQ',
  },
  {
    problem: 'Concatenated Words',
    pattern: '1-D Dynamic Programming',
    link: 'concatenated-words/',
    difficulty: 'hard',
    video: 'iHp7fjw1R28',
  },
  {
    problem: 'Maximize Score after N Operations',
    pattern: '1-D Dynamic Programming',
    link: 'maximize-score-after-n-operations/',
    difficulty: 'hard',
    video: 'RRQVDqp5RSE',
  },
  {
    problem: 'Find the Longest Valid Obstacle Course at Each Position ',
    pattern: '1-D Dynamic Programming',
    link: 'find-the-longest-valid-obstacle-course-at-each-position/',
    difficulty: 'hard',
    video: 'Xq9VT7p0lic',
  },
  {
    problem: 'Unique Paths',
    pattern: '2-D Dynamic Programming',
    link: 'unique-paths/',
    difficulty: 'medium',
    video: 'IlEsdxuD4lY',
  },
  {
    problem: 'Unique Paths II',
    pattern: '2-D Dynamic Programming',
    link: 'unique-paths-ii/',
    difficulty: 'medium',
    video: 'd3UOz7zdE4I',
  },
  {
    problem: 'Longest Common Subsequence',
    pattern: '2-D Dynamic Programming',
    link: 'longest-common-subsequence/',
    difficulty: 'medium',
    video: 'Ua0GhsJSlWM',
  },
  {
    problem: 'Longest Palindromic Subsequence',
    pattern: '2-D Dynamic Programming',
    link: 'longest-palindromic-subsequence/',
    difficulty: 'medium',
    video: 'bUr8cNWI09Q',
  },
  {
    problem: 'Last Stone Weight II',
    pattern: '2-D Dynamic Programming',
    link: 'last-stone-weight-ii/',
    difficulty: 'medium',
    video: 'gdXkkmzvR3c',
  },
  {
    problem: 'Best Time to Buy And Sell Stock With Cooldown',
    pattern: '2-D Dynamic Programming',
    link: 'best-time-to-buy-and-sell-stock-with-cooldown/',
    difficulty: 'medium',
    video: 'I7j0F7AHpb8',
  },
  {
    problem: 'Coin Change II',
    pattern: '2-D Dynamic Programming',
    link: 'coin-change-ii/',
    difficulty: 'medium',
    video: 'Mjy4hd2xgrs',
  },
  {
    problem: 'Target Sum',
    pattern: '2-D Dynamic Programming',
    link: 'target-sum/',
    difficulty: 'medium',
    video: 'g0npyaQtAQM',
  },
  {
    problem: 'Interleaving String',
    pattern: '2-D Dynamic Programming',
    link: 'interleaving-string/',
    difficulty: 'medium',
    video: '3Rw3p9LrgvE',
  },
  {
    problem: 'Stone Game',
    pattern: '2-D Dynamic Programming',
    link: 'stone-game/',
    difficulty: 'medium',
    video: 'uhgdXOlGYqE',
  },
  {
    problem: 'Minimum Path Sum',
    pattern: '2-D Dynamic Programming',
    link: 'minimum-path-sum/',
    difficulty: 'medium',
    video: 'pGMsrvt0fpk',
  },
  {
    problem: 'Longest Increasing Path In a Matrix',
    pattern: '2-D Dynamic Programming',
    link: 'longest-increasing-path-in-a-matrix/',
    difficulty: 'hard',
    video: 'wCc_nd-GiEc',
  },
  {
    problem: 'Maximal Square',
    pattern: '2-D Dynamic Programming',
    link: 'maximal-square/',
    difficulty: 'medium',
    video: '6X7Ha2PrDmM',
  },
  {
    problem: 'Ones and Zeroes',
    pattern: '2-D Dynamic Programming',
    link: 'ones-and-zeroes/',
    difficulty: 'medium',
    video: 'miZ3qV04b1g',
  },
  {
    problem: 'Maximum Alternating Subsequence Sum',
    pattern: '2-D Dynamic Programming',
    link: 'maximum-alternating-subsequence-sum/',
    difficulty: 'medium',
    video: '4v42XOuU1XA',
  },
  {
    problem: 'Distinct Subsequences',
    pattern: '2-D Dynamic Programming',
    link: 'distinct-subsequences/',
    difficulty: 'hard',
    video: '-RDzMJ33nx8',
  },
  {
    problem: 'Edit Distance',
    pattern: '2-D Dynamic Programming',
    link: 'edit-distance/',
    difficulty: 'hard',
    video: 'XYi2-LPrwm4',
  },
  {
    problem: 'Count Vowels Permutation',
    pattern: '2-D Dynamic Programming',
    link: 'count-vowels-permutation/',
    difficulty: 'hard',
    video: 'VUVpTZVa7Ls',
  },
  {
    problem: 'Burst Balloons',
    pattern: '2-D Dynamic Programming',
    link: 'burst-balloons/',
    difficulty: 'hard',
    video: 'VFskby7lUbw',
  },
  {
    problem: 'Number of Ways to Rearrange Sticks With K Sticks Visible',
    pattern: '2-D Dynamic Programming',
    link: 'number-of-ways-to-rearrange-sticks-with-k-sticks-visible/',
    difficulty: 'hard',
    video: 'O761YBjGxGA',
  },
  {
    problem: 'Regular Expression Matching',
    pattern: '2-D Dynamic Programming',
    link: 'regular-expression-matching/',
    difficulty: 'hard',
    video: 'HAA8mgxlov8',
  },
  {
    problem: 'Stone Game II',
    pattern: '2-D Dynamic Programming',
    link: 'stone-game-ii/',
    difficulty: 'medium',
    video: 'I-z-u0zfQtg',
  },
  {
    problem: 'Flip String to Monotone Increasing',
    pattern: '2-D Dynamic Programming',
    link: 'flip-string-to-monotone-increasing/',
    difficulty: 'medium',
    video: 'tMq9z5k3umQ',
  },
  {
    problem: 'Maximum Value of K Coins from Piles',
    pattern: '2-D Dynamic Programming',
    link: 'maximum-value-of-k-coins-from-piles/',
    difficulty: 'hard',
    video: 'ZRdEd_eun8g',
  },
  {
    problem: 'Number of Ways to Form a Target String Given a Dictionary',
    pattern: '2-D Dynamic Programming',
    link: 'number-of-ways-to-form-a-target-string-given-a-dictionary/',
    difficulty: 'hard',
    video: '_GF-0T-YjW8',
  },
  {
    problem: 'Profitable Schemes',
    pattern: '2-D Dynamic Programming',
    link: 'profitable-schemes/',
    difficulty: 'hard',
    video: 'CcLKQLKvOl8',
  },
  {
    problem: 'Minimum Cost to Cut a Stick',
    pattern: '2-D Dynamic Programming',
    link: 'minimum-cost-to-cut-a-stick/',
    difficulty: 'hard',
    video: 'EVxTO5I0d7w',
  },
  {
    problem: 'Maximum Subarray',
    pattern: 'Greedy',
    link: 'maximum-subarray/',
    difficulty: 'medium',
    video: '5WZl3MMT0Eg',
  },
  {
    problem: 'Maximum Sum Circular Subarray',
    pattern: 'Greedy',
    link: 'maximum-sum-circular-subarray/',
    difficulty: 'medium',
    video: 'fxT9KjakYPM',
  },
  {
    problem: 'Longest Turbulent Array',
    pattern: 'Greedy',
    link: 'longest-turbulent-subarray/',
    difficulty: 'medium',
    video: 'V_iHUhR8Dek',
  },
  {
    problem: 'Jump Game',
    pattern: 'Greedy',
    link: 'jump-game/',
    difficulty: 'medium',
    video: 'Yan0cv2cLy8',
  },
  {
    problem: 'Jump Game II',
    pattern: 'Greedy',
    link: 'jump-game-ii/',
    difficulty: 'medium',
    video: 'dJ7sWiOoK7g',
  },
  {
    problem: 'Jump Game VII',
    pattern: 'Greedy',
    link: 'jump-game-vii/',
    difficulty: 'medium',
    video: 'v1HpZUnQ4Yo',
  },
  {
    problem: 'Gas Station',
    pattern: 'Greedy',
    link: 'gas-station/',
    difficulty: 'medium',
    video: 'lJwbPZGo05A',
  },
  {
    problem: 'Hand of Straights',
    pattern: 'Greedy',
    link: 'hand-of-straights/',
    difficulty: 'medium',
    video: 'amnrMCVd2YI',
  },
  {
    problem: 'Minimize Maximum of Array',
    pattern: 'Greedy',
    link: 'minimize-maximum-of-array/',
    difficulty: 'medium',
    video: 'AeHMvcKuR0Y',
  },
  {
    problem: 'Dota2 Senate',
    pattern: 'Greedy',
    link: 'dota2-senate/',
    difficulty: 'medium',
    video: 'zZA5KskfMuQ',
  },
  {
    problem: 'Maximum Points You Can Obtain From Cards',
    pattern: 'Greedy',
    link: 'maximum-points-you-can-obtain-from-cards/',
    difficulty: 'medium',
    video: 'TsA4vbtfCvo',
  },
  {
    problem: 'Merge Triplets to Form Target Triplet',
    pattern: 'Greedy',
    link: 'merge-triplets-to-form-target-triplet/',
    difficulty: 'medium',
    video: 'kShkQLQZ9K4',
  },
  {
    problem: 'Partition Labels',
    pattern: 'Greedy',
    link: 'partition-labels/',
    difficulty: 'medium',
    video: 'B7m8UmZE-vw',
  },
  {
    problem: 'Valid Parenthesis String',
    pattern: 'Greedy',
    link: 'valid-parenthesis-string/',
    difficulty: 'medium',
    video: 'QhPdNS143Qg',
  },
  {
    problem: 'Eliminate Maximum Number of Monsters',
    pattern: 'Greedy',
    link: 'eliminate-maximum-number-of-monsters/',
    difficulty: 'medium',
    video: '6QQRayzOTD4',
  },
  {
    problem: 'Two City Scheduling',
    pattern: 'Greedy',
    link: 'two-city-scheduling/',
    difficulty: 'medium',
    video: 'd-B_gk_gJtQ',
  },
  {
    problem: 'Insert Interval',
    pattern: 'Intervals',
    link: 'insert-interval/',
    difficulty: 'medium',
    video: 'A8NUOmlwOlM',
  },
  {
    problem: 'Merge Intervals',
    pattern: 'Intervals',
    link: 'merge-intervals/',
    difficulty: 'medium',
    video: '44H3cEC2fFM',
  },
  {
    problem: 'Non Overlapping Intervals',
    pattern: 'Intervals',
    link: 'non-overlapping-intervals/',
    difficulty: 'medium',
    video: 'nONCGxWoUfM',
  },
  {
    problem: 'Meeting Rooms',
    pattern: 'Intervals',
    link: 'meeting-rooms/',
    difficulty: 'easy',
    video: 'PaJxqZVPhbg',
  },
  {
    problem: 'Meeting Rooms II',
    pattern: 'Intervals',
    link: 'meeting-rooms-ii/',
    difficulty: 'medium',
    video: 'FdzJmTCVyJU',
  },
  {
    problem: 'Remove Covered Intervals',
    pattern: 'Intervals',
    link: 'remove-covered-intervals/',
    difficulty: 'medium',
    video: 'nhAsMabiVkM',
  },
  {
    problem: 'Minimum Interval to Include Each Query',
    pattern: 'Intervals',
    link: 'minimum-interval-to-include-each-query/',
    difficulty: 'hard',
    video: '5hQ5WWW5awQ',
  },
  {
    problem: 'Data Stream as Disjoint Intervals',
    pattern: 'Intervals',
    link: 'data-stream-as-disjoint-intervals/',
    difficulty: 'hard',
    video: 'FavoZjPIWpo',
  },
  {
    problem: 'Greatest Common Divisor of Strings',
    pattern: 'Math & Geometry',
    link: 'greatest-common-divisor-of-strings/',
    difficulty: 'easy',
    video: 'i5I_wrbUdzM',
  },
  {
    problem: 'Count Odd Numbers in an Interval Range',
    pattern: 'Math & Geometry',
    link: 'count-odd-numbers-in-an-interval-range/',
    difficulty: 'easy',
    video: 'wrIWye928JQ',
  },
  {
    problem: 'Matrix Diagonal Sum',
    pattern: 'Math & Geometry',
    link: 'matrix-diagonal-sum/',
    difficulty: 'easy',
    video: 'WliTu6gIK7o',
  },
  {
    problem: 'Maximum Points on a Line',
    pattern: 'Math & Geometry',
    link: 'max-points-on-a-line/',
    difficulty: 'hard',
    video: 'Bb9lOXUOnFw',
  },
  {
    problem: 'Rotate Image',
    pattern: 'Math & Geometry',
    link: 'rotate-image/',
    difficulty: 'medium',
    video: 'fMSJSS7eO1w',
  },
  {
    problem: 'Spiral Matrix',
    pattern: 'Math & Geometry',
    link: 'spiral-matrix/',
    difficulty: 'medium',
    video: 'BJnMZNwUk1M',
  },
  {
    problem: 'Spiral Matrix II ',
    pattern: 'Math & Geometry',
    link: 'spiral-matrix-ii/',
    difficulty: 'medium',
    video: 'RvLrWFBJ9fM',
  },
  {
    problem: 'Set Matrix Zeroes',
    pattern: 'Math & Geometry',
    link: 'set-matrix-zeroes/',
    difficulty: 'medium',
    video: 'T41rL0L3Pnw',
  },
  {
    problem: 'Happy Number',
    pattern: 'Math & Geometry',
    link: 'happy-number/',
    difficulty: 'easy',
    video: 'ljz85bxOYJ0',
  },
  {
    problem: 'Plus One',
    pattern: 'Math & Geometry',
    link: 'plus-one/',
    difficulty: 'easy',
    video: 'jIaA8boiG1s',
  },
  {
    problem: 'Palindrome Number',
    pattern: 'Math & Geometry',
    link: 'palindrome-number/',
    difficulty: 'easy',
    video: 'yubRKwixN-U',
  },
  {
    problem: 'Ugly Number',
    pattern: 'Math & Geometry',
    link: 'ugly-number/',
    difficulty: 'easy',
    video: 'M0Zay1Qr9ws',
  },
  {
    problem: 'Shift 2D Grid',
    pattern: 'Math & Geometry',
    link: 'shift-2d-grid/',
    difficulty: 'easy',
    video: 'nJYFh4Dl-as',
  },
  {
    problem: 'Roman to Integer',
    pattern: 'Math & Geometry',
    link: 'roman-to-integer/',
    difficulty: 'easy',
    video: '3jdxYj3DD98',
  },
  {
    problem: 'Integer to Roman',
    pattern: 'Math & Geometry',
    link: 'integer-to-roman/',
    difficulty: 'medium',
    video: 'ohBNdSJyLh8',
  },
  {
    problem: 'Pow(x, n)',
    pattern: 'Math & Geometry',
    link: 'powx-n/',
    difficulty: 'medium',
    video: 'g9YQyYi4IQQ',
  },
  {
    problem: 'Multiply Strings',
    pattern: 'Math & Geometry',
    link: 'multiply-strings/',
    difficulty: 'medium',
    video: '1vZswirL8Y8',
  },
  {
    problem: 'Detect Squares',
    pattern: 'Math & Geometry',
    link: 'detect-squares/',
    difficulty: 'medium',
    video: 'bahebearrDc',
  },
  {
    problem: 'Robot Bounded In Circle',
    pattern: 'Math & Geometry',
    link: 'robot-bounded-in-circle/',
    difficulty: 'medium',
    video: 'nKv2LnC_g6E',
  },
  {
    problem: 'Zigzag Conversion',
    pattern: 'Math & Geometry',
    link: 'zigzag-conversion/',
    difficulty: 'medium',
    video: 'Q2Tw6gcVEwc',
  },
  {
    problem: 'Find Missing Observations',
    pattern: 'Math & Geometry',
    link: 'find-missing-observations/',
    difficulty: 'medium',
    video: '86yKkaNi3sU',
  },
  {
    problem: 'Single Number',
    pattern: 'Bit Manipulation',
    link: 'single-number/',
    difficulty: 'easy',
    video: 'qMPX1AOa83k',
  },
  {
    problem: 'Number of 1 Bits',
    pattern: 'Bit Manipulation',
    link: 'number-of-1-bits/',
    difficulty: 'easy',
    video: '5Km3utixwZs',
  },
  {
    problem: 'Counting Bits',
    pattern: 'Bit Manipulation',
    link: 'counting-bits/',
    difficulty: 'easy',
    video: 'RyBM56RIWrM',
  },
  {
    problem: 'Reverse Bits',
    pattern: 'Bit Manipulation',
    link: 'reverse-bits/',
    difficulty: 'easy',
    video: 'UcoN6UjAI64',
  },
  {
    problem: 'Missing Number',
    pattern: 'Bit Manipulation',
    link: 'missing-number/',
    difficulty: 'easy',
    video: 'WnPLSRLSANE',
  },
  {
    problem: 'Shuffle the Array',
    pattern: 'Bit Manipulation',
    link: 'shuffle-the-array/',
    difficulty: 'easy',
    video: 'IvIKD_EU8BY',
  },
  {
    problem: 'Add to Array-Form of Integer',
    pattern: 'Bit Manipulation',
    link: 'add-to-array-form-of-integer/',
    difficulty: 'easy',
    video: 'eBTZQt1TWfk',
  },
  {
    problem: 'Sum of Two Integers',
    pattern: 'Bit Manipulation',
    link: 'sum-of-two-integers/',
    difficulty: 'medium',
    video: 'gVUrDV4tZfY',
  },
  {
    problem: 'Reverse Integer',
    pattern: 'Bit Manipulation',
    link: 'reverse-integer/',
    difficulty: 'medium',
    video: 'HAgLH58IgJQ',
  },
  {
    problem: 'Add Binary',
    pattern: 'Bit Manipulation',
    link: 'add-binary/',
    difficulty: 'easy',
    video: 'keuWJ47xG8g',
  },
  {
    problem: 'Create Hello World Function',
    pattern: 'JavaScript',
    link: 'create-hello-world-function/',
    difficulty: 'easy',
    video: 'P9Ldx1eTlRc',
  },
  {
    problem: 'Counter',
    pattern: 'JavaScript',
    link: 'counter/',
    difficulty: 'easy',
    video: 'yEGQQAG5V68',
  },
  {
    problem: 'Counter II',
    pattern: 'JavaScript',
    link: 'counter-ii/',
    difficulty: 'easy',
    video: 'UXNXKGFZD08',
  },
  {
    problem: 'Apply Transform over each Element in Array',
    pattern: 'JavaScript',
    link: 'apply-transform-over-each-element-in-array/',
    difficulty: 'easy',
    video: '7FhJHA5jlYk',
  },
  {
    problem: 'Filter Elements from Array',
    pattern: 'JavaScript',
    link: 'filter-elements-from-array/',
    difficulty: 'easy',
    video: 'w1o81gbEEJU',
  },
  {
    problem: 'Array Reduce Transformation',
    pattern: 'JavaScript',
    link: 'array-reduce-transformation/',
    difficulty: 'easy',
    video: 'KmTbYfpGxdM',
  },
  {
    problem: 'Function Composition',
    pattern: 'JavaScript',
    link: 'function-composition/',
    difficulty: 'easy',
    video: 'mIFw1H7Ljco',
  },
  {
    problem: 'Allow One Function Call',
    pattern: 'JavaScript',
    link: 'allow-one-function-call/',
    difficulty: 'easy',
    video: 'm_SWhM9iX3s',
  },
  {
    problem: 'Memoize',
    pattern: 'JavaScript',
    link: 'memoize/',
    difficulty: 'medium',
    video: 'oFXyzJt9VeU',
  },
  {
    problem: 'Curry',
    pattern: 'JavaScript',
    link: 'curry/',
    difficulty: 'medium',
    video: 'pi4kqMWQXxA',
  },
  {
    problem: 'Sleep',
    pattern: 'JavaScript',
    link: 'sleep/',
    difficulty: 'easy',
    video: 'P0D9Z6H7O00',
  },
  {
    problem: 'Promise Time Limit',
    pattern: 'JavaScript',
    link: 'promise-time-limit/',
    difficulty: 'easy',
    video: 'hfH57rdZhOk',
  },
  {
    problem: 'Promise Pool',
    pattern: 'JavaScript',
    link: 'promise-pool/',
    difficulty: 'medium',
    video: 'DB8pAAg-9xw',
  },
  {
    problem: 'Cache With Time Limit',
    pattern: 'JavaScript',
    link: 'cache-with-time-limit/',
    difficulty: 'medium',
    video: 'w772gtNK0Gw',
  },
  {
    problem: 'Debounce',
    pattern: 'JavaScript',
    link: 'debounce/',
    difficulty: 'medium',
    video: '1sxSpnxNx5w',
  },
  {
    problem: 'Throttle',
    pattern: 'JavaScript',
    link: 'throttle/',
    difficulty: 'medium',
    video: 'zyGZV_fIQWk',
  },
  {
    problem: 'JSON Deep Equal',
    pattern: 'JavaScript',
    link: 'json-deep-equal/',
    difficulty: 'medium',
    video: '4JVZ-mVqJPg',
  },
  {
    problem: 'Convert Object to JSON String',
    pattern: 'JavaScript',
    link: 'convert-object-to-json-string/',
    difficulty: 'medium',
    video: 'f94fUbHU-FY',
  },
  {
    problem: 'Array of Objects to Matrix',
    pattern: 'JavaScript',
    link: 'array-of-objects-to-matrix/',
    difficulty: 'medium',
    video: 'LJwgAMHGcI0',
  },
  {
    problem: 'Difference Between Two Objects',
    pattern: 'JavaScript',
    link: 'differences-between-two-objects/',
    difficulty: 'medium',
    video: 'gH7oZs1WZfg',
  },
  {
    problem: 'Chunk Array',
    pattern: 'JavaScript',
    link: 'chunk-array/',
    difficulty: 'easy',
    video: 'VUN-O3B9ceY',
  },
  {
    problem: 'Flatten Deeply Nested Array',
    pattern: 'JavaScript',
    link: 'flatten-deeply-nested-array/',
    difficulty: 'medium',
    video: '_DetLPKtFNk',
  },
  {
    problem: 'Array Prototype Last',
    pattern: 'JavaScript',
    link: 'array-prototype-last/',
    difficulty: 'easy',
    video: '3JdtfMBrUqc',
  },
  {
    problem: 'Group By',
    pattern: 'JavaScript',
    link: 'group-by/',
    difficulty: 'medium',
    video: 'zs9axOyYHRE',
  },
  {
    problem: 'Check if Object Instance of Class',
    pattern: 'JavaScript',
    link: 'check-if-object-instance-of-class/',
    difficulty: 'medium',
    video: 'meIo-Q07Ba8',
  },
  {
    problem: 'Call Function with Custom Context',
    pattern: 'JavaScript',
    link: 'call-function-with-custom-context/',
    difficulty: 'medium',
    video: 'du_GH-Ooa8E',
  },
  {
    problem: 'Event Emitter',
    pattern: 'JavaScript',
    link: 'event-emitter/',
    difficulty: 'medium',
    video: 'M69bjWFarU0',
  },
  {
    problem: 'Array Wrapper',
    pattern: 'JavaScript',
    link: 'array-wrapper/',
    difficulty: 'easy',
    video: 'XoGjPdPTAVA',
  },
  {
    problem: 'Generate Fibonacci Sequence',
    pattern: 'JavaScript',
    link: 'generate-fibonacci-sequence/',
    difficulty: 'easy',
    video: 'T643rQ70Jlk',
  },
  {
    problem: 'Nested Array Generator',
    pattern: 'JavaScript',
    link: 'nested-array-generator/',
    difficulty: 'medium',
    video: 'yo-J1jQaZYU',
  },
];
